### PR TITLE
Add dirty tracking

### PR DESCRIPTION
**Pull request by senid231**
this PR allows to use dirty attributes/relationships tracking (similar as it done in ActiveModel)
~~and add class attribute read_only_relations similar to read_only_attributes~~

inspired by #58 and my own desire to use this gem with jsonapi-resources on server side

### CODE REVIEW

**Comment by senid231** [comment]
maybe i should add some additional tests on read_only_relations and dirty tracking features ?

**Comment by senid231** [comment]
ability to set read_only relationships was moved to PR #92 (with some additional fixes)

**Comment by senid231** [comment]
@chingor13 can you review PRs #90 and #92 ?

**Comment by chingor13** [comment]
Thanks, I'm going to change `clear_dirty_attributes` -> `clear_changes_information`

**Pull request merged**
