### PR TITLE
Taking status code from actual http response rather than meta section.

### PR DESCRIPTION
**Pull request by theirishpenguin**
Note: Need to tidy and add tests if this is in the right direction.

### CODE REVIEW

**Comment by chingor13** [comment]
It's already handling the status from the response (env) on [line 6](https://github.com/theirishpenguin/json_api_client/blob/penguin/fix-135-get-http-status-code-from-actual-response/lib/json_api_client/middleware/status.rb#L6). The second block is in case there's a meta[status] section (which was an example in an older version of the spec)

**Comment by chingor13** [comment]
We can add the NotAuthorized error type if you want to separate that into it's own PR

**Comment by theirishpenguin** [comment]
Thanks @chingor13. This wasn't working for me the other day - but I will debug/investigate the area of the code you have mentioned in your comment (sometime this week hopefully) and get back to you.

**Comment by theirishpenguin** [comment]
Just looked at this again. Ya, it will just the fact that the NotAuthorized error type was not being handled. I'll fire a PR together, cheers.

**Pull request closed without merging**
