### PR TITLE
Fixed: query builder respects custom pagination params

### PR DESCRIPTION
**Pull request by kdonovan**
Fixes an issue I was running into where the custom pagination params I set weren't being used when generating pagination queries.

### CODE REVIEW

**Comment by chingor13** [comment]
Can you make this test a separate one with a separate test resource? This changes the behavior of that one test and we lose it's original intent.

**Comment by kdonovan** [comment]
Can do -- just added a new file for the param name test.

**Comment by ouranos** [comment]
@chingor13 @kdonovan this seems to introduce a regression as the default pagination params are now `page` and `per_page` as defined in [`JsonApiClient::Paginating::Paginator`](https://github.com/chingor13/json_api_client/blob/master/lib/json_api_client/paginating/paginator.rb#L7).
Before this change it was `number` and `size`.

**Comment by kdonovan** [comment]
I feel like page/per_page is more in line with standard Rails defaults, but good catch -- that should have been documented better. 

Thanks for providing the initializer fix for anyone bitten by that change!

**Pull request merged**
