### PR TITLE
Add time type

### PR DESCRIPTION
**Pull request by dennisfaust**

### CODE REVIEW

**Comment by dennisfaust** [comment]
Still working on this. Merged with master but not json_api_1_0. Working through that now.

**Comment by chingor13** [comment]
Could you possibly move the test to a different example class? I would like to keep the Article, Person and Comment classes clean because the examples are coming directly from the JSON-API documentation spec.

**Comment by dennisfaust** [comment]
Moved the coercion tests into their own file so as not to pollute the example models and make the whole thing more explicit.

**Comment by chingor13** [comment]
ported this directly into master because I didn't want to deal with the merge conflict. let me know if I missed parts.

**Pull request closed without merging**
