### PR TITLE
Raise client error for unhandled 4xx responses

### PR DESCRIPTION
**Pull request by jamesstonehill**
Resolves https://github.com/JsonApiClient/json_api_client/issues/308

### CODE REVIEW

**Comment by gaorlov** [comment]
This looks solid. Thank you so much for the contribution! Can you take a look and see if the test failures are due to your changes?

**Comment by jamesstonehill** [comment]
Doesn't look like it. Looks like some kind of test file load order thing.

**Comment by gaorlov** [comment]
@jamesstonehill those are the worst. Alright. Rerunning seems to have fixed it. I'll take a look later. Thanks!

**Comment by gaorlov** [comment]
Oh. One last thing: can you add a description to the `Changelog.md`?

**Comment by gaorlov** [comment]
@jamesstonehill 1.6.2 is live

**Comment by marybethlee** [comment]
This is causing `422` errors to raise a client error again, which was something that was reverted in this commit: https://github.com/JsonApiClient/json_api_client/commit/819531aed6e454f26ef7d3944d9bcb4bfaeacdc3#diff-a5876160692c35f965ad9d0dc8d46f69

422 errors are usually used for resource validation errors, should that particular status be excluded from the ClientError?

**Comment by jamesstonehill** [comment]
Why was that reverted? Raising an error may not be the best way to handle a 422 but it's far better than failing silently.

**Comment by marybethlee** [comment]
I think most people would expect `422` to not raise an error, because the response is returning errors on the resource, and the gem is handling that appropriately -- the `model.errors` is filled with the data from the response

To not break compatibility for now, the easiest would be to not raise on `422` errors, and a more customized approach would be to allow users to configure how they want 4xx errors to behave

**Comment by jamesstonehill** [comment]
Yeah, that's a good point. Since these responses would populate the model errors raising probably isn't right here. Probably best to revert.

**Comment by marybethlee** [comment]
@jamesstonehill I think raising on the other 4xx errors is appropriate, it's just the 422 that should be ignored.

**Comment by jamesstonehill** [comment]
Are there any other 4xx statuses that might return validation errors?

**Comment by jamesstonehill** [comment]
https://github.com/JsonApiClient/json_api_client/pull/312/files

**Comment by marybethlee** [comment]
I'm not sure if there are other statuses that might return validation errors, and the [json api spec](http://jsonapi.org/format/#errors-processing) isn't specific about the 4xx errors, but 422 seems generally accepted.

**Comment by gaorlov** [comment]
I think it's reasonable to allow them as they come up

**Pull request merged**
